szabgab/perlweekly

src/199.json
Every time I do this, I say I won't be finishing after midnight on Sunday ... :-)
Cheers,
Neil
=> Issue number 199 - Monday 18th May 2015

src/199.json
I didn't write the sentence I meant to. The sentence that went out wasn't as positive as I intended.
I've emailed Dave apologising for it, but he said "no worries!". I said I'd ask you to update the online version.
=> incomplete thought on Dave Mitchell entry

src/200.json
Fix link to brian d foy article.
=> Link to Perl 5.22 new features

src/231.json, src/authors.json
Hi Gabor,
The final issue of 2015!
Cheers,
Neil
=> Issue 231, the last of 2015

src/authors.json
Per this tweet: https://twitter.com/szabgab/status/710556608540119040
I added mine.
=> added my twitter handle

src/authors.json
What should be the behaviour if I know the twitter account for someone else?
=> Added details for polettix

html/archive/247.html, html/perlweekly.rss, src/247.json
Hi @szabgab and all!
This is a pull-req with some corrections . Please consider applying it.
=> Some spelling/grammar/etc. corrections.

html/archive/250.html, html/perlweekly.rss, src/250.json
Hi! This pull-req corrects some typos. Please merge.
=> Correct some typos.

src/263.json
=> fREW's blog post is written by fREW & Ribasushi, both

src/266.json
I did not try to build the site with it because the instructions in the README.md were too confusing.
=> Fix some broken grammar in #266.

src/273.json
Hi! Here are some corrections to typos I found. Please consider merging.
=> Correct some spelling errors.

src/280.json
Hi Gabor,
Here's issue 280!
Cheers,
Neil
=> Issue 280 - December 5th

src/300.json, src/authors.json
Hi Gabor,
Wow, issue 300 -- pretty cool that I got to be editor for this one.
Thanks for starting this, back in August 2011!
Cheers,
Neil
=> Issue 300!

src/301.json
=> Correct spelling

tt/webpage.tt
Not necessarily ready to be merged but wanted to get some feedback if you would like this addition of buttons for saving to pocket.
note for testing; chrome will block the pocket js code due to loading insecure content by default.
=> adds the pocket button to each article link

src/331.json
Hi Gabor,
Here's issue 331!
Cheers,
Neil
=> Issue 331 -- LPW news coming in

src/333.json
I kept the advent calendars' links intact, it is too hard for me to pick up the best ones.
Thanks.
=> Issue #333

src/347.json, src/authors.json
=> Issue #347

src/348.json, src/authors.json
Hi,
I saw only one Perl Maven article & it is pro, so I was unsure about putting it here (because it is pro). You please make the decision.
Thanks.
=> Issue 348 (Please mention Perl Maven articles)

src/356.json
Hi Gabor,
Please review the draft for next edition of Perl Weekly newsletter.
As this is my first edition, I will be better prepared with more juicy stuff next time.
Many Thanks.
Best Regards,
=> First draft for issue #356.

src/358.json, src/authors.json
Hi Gabor,
Please review the draft for #358 edition of PerlWeekly newsletter.
Many Thanks.
Best Regards,
=> Proposed draft for #358 edition of PerlWeekly newsletter.

src/360.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #360.

src/362.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Draft for the next issue #362 of PerlWeekly.

src/364.json, src/authors.json
Hi Gabor,
Please review the draft for the next week newsletter.
Many Thanks.
Best Regards,
Mohammad S Amwar
=> Draft for the next issue 364.

src/366.json, src/authors.json
Hi @szabgab 
Please review the draft for the next issue #366 of PerlWeekly.
Many Thanks.
Best Regards,
=> Draft for the next issue #366 of PerlWeekly.

src/368.json, src/authors.json
Hi @szabgab 
Please review the draft for the next week newsletter #368.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #368.

src/370.json, src/authors.json
Hi @szabgab 
Please review the draft for next week newsletter #370.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #370.

src/372.json, src/authors.json
Hi @szabgab 
Please review the draft for next week PerlWeekly newsletter.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #372.

tt/index.tt
Hi @szabgab 
Added blurb for myself as suggested. Please review the text.
Many Thanks.
Best Regards,
=> Added blurb for Mohammad Anwar.

src/373.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Fixed broken link to CFP Perl Advent.

src/374.json, src/authors.json
Hi @szabgab 
Apology for late submission.
Many Thanks
Best Regards,
=> Proposed draft for next week newsletter #374.

src/376.json, src/authors.json
Hi @szabgab 
Many Thanks
Best Regards,
=> Proposed draft for next week newsletter #376.

src/380.json, src/authors.json
Hi @szabgab 
Please review the draft for the next week newsletter #380.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #380.

src/382.json, src/authors.json
Hi @szabgab 
Please review the draft for the next week newsletter #382.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #382.

src/384.json, src/authors.json
Hi @szabgab 
Please review the draft for the next week newsletter.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #384.

src/386.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #386.

src/388.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #388.

src/390.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #390.

src/392.json, src/authors.json
Hi @szabgab 
Please review the proposed draft for next week newsletter.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #392.

src/394.json, src/authors.json
Hi @szabgab 
Please review the draft for the next week newsletter.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #394.

src/396.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #396.

src/398.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #398.

src/400.json
Hi @szabgab 
I have introduced new section "Perl Weekly Challenge", hope you don't mind it.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #400.

src/402.json, src/authors.json
Hi @szabgab 
I have added placeholder link to next week challenge. It will be live midnight tonight.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #402.

src/404.json, src/authors.json
Hi @szabgab 
For Perl Weekly Challenge, I have added 2 links, one for Challenge 005 and another for RECAP Challenge 004. These will become active tonight.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #404.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Fixed typo in author name.

src/406.json
Hi @szabgab 
Please review the draft for the next week newsletter.
Apology for the delay, as I deleted the json just before the commit by mistake (meant to delete the html file). I had to re-create again from the generated html page.
Not much content like last week except for Perl Weekly Challenge and Perl Toolchain Summit report.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #406.

src/408.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #408.

src/authors.json
Hi @szabgab,
I have added new member that has an entry in the JSON for the next Perl Weekly Challenge. I will send you the JSON shortly.
Many Thanks.
Best Regards,
=> Added member Yozen Hernandez.

src/410.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #410.

src/412.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #412.

src/authors.json
Hi @szabgab 
Added couple of new authors needed for next week JSON for Perl Weekly Challenge.
Many Thanks.
Best Regards,
=> Added new authors.

src/414.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #414.

src/416.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #416.

src/418.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #418.

src/420.json, src/authors.json
Hi @szabgab 
Please review the draft for next newsletter.
Apology for late submission.
Best Regards,
=> Proposed draft for next week newsletter #420.

src/422.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #422.

src/424.json
Hi @szabgab 
Please review the draf.
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #424.

src/next.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Updated template for "Perl Weekly Challenge" section.

src/428.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #428.

src/430.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #430.

src/authors.json
Hi @szabgab 
Please review the PR to add new author Javier Luque.
Many Thanks.
Best Regards,
=> Added author Javier Luque.

src/432.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #432.

src/434.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #434.

src/436.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #436.

src/438.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #438.

src/authors.json
Hi @szabgab 
I needed this author for next week newsletter.
Many Thanks.
Best Regards,
=> Added author Ryan Thompson.

src/440.json
Hi @szabgab 
First of all, I wish you a very happy new year.
Many Thanks.
Best Regards,
=> Draft for next week newsletter.

src/442.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #442.

src/444.json
Hi @szabgab 
Apology for not completing the newsletter as I was attending my Dad in India. I am flying back today.
Please help me with it this time.
Best Regards,
=> - Half baked work, sorry :-(

src/446.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #446.

src/448.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #448.

src/450.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #450.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Added new author Shahed Nooshmand.

src/454.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #454.

src/456.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #456.

src/458.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #458.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Added new author Colin Crain.

src/460.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #460.

src/462.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Proposed draft for next week newsletter #462.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
=> Added author Bartosz Jarzyn.

src/464.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #464.

src/466.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #466.

src/468.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #468.

docs/perlweekly.rss, lib/PerlWeekly/Issue.pm
This looks, to me, like it fixes #283
=> Double-encoding in RSS feed

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added author Simon Green for Perl Weekly Challenge.

src/470.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #470.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added author Walt Mankowski for Perl Weekly Challenge.

src/472.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #472.

src/474.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #474.

src/476.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #476.

src/478.json
Hi @szabgab 
Many Thanks.
best Regards,
Mohammad
=> Proposed draft for next week newsletter #478.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added author Daniel Mantovani for PWC.

src/events.json
BTW, I've done this kind of thing in the past (JSON config file with pull
requests). What will likely happen is that if this gets busy you'll have a lot
of merge conflicts, since most people will be editing the same point in the
same file. Having said that, thanks for doing this! :)
=> Add next event for Toronto Perl Mongers

src/events.json
I would like to add our Houston Perl Mongers meeting to the list.
=> Added October Houston PerlMongers meeting

src/480.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #480.

src/480.json
I started by correcting Damian's name - but then I got a bit carried away :-/
=> Light copyedit

tt/index.tt
I was looking for something completely different (see the issue I'm about to raise) but while looking, I found a number of HTTP links on your index page that could be HTTPS. So I fixed them.
=> Replaced a load of HTTP links with their HTTPS version

src/482.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #482.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added new PWC author Dieter Dobbelaere.

src/484.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #484.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added pwc author Jorg Sommrey.

src/486.json, src/authors.json
Hi @szabgab 
Apology for the delay.
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #486.

src/488.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #488.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added authors Aaron Smith and Luis Mochan.

src/490.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #490.

src/492.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #492.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Add author mimosinnet

src/494.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #494.

src/496.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #496.

src/498.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #498.

src/500.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #500.

src/events.json
Announcing our March meeting and asking for lightning talks.
=> march lightning talks

src/502.json
Hi @szabgab 
Msny Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #502.

src/504.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #504.

src/events.json
=> Added April Houston PM Event

src/506.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #506.

docs/index.html, tt/index.tt
Hello,
Edit URL for gh meets CPAN :)
=> Edit URL for github-meets-cpan

src/508.json, src/authors.json
Hi @szabgab 
Apology for the delay.
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #508.

src/510.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #510.

src/512.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #512.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added new author Christian Jaeger for PWC.

src/514.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #514.

src/516.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #516.

src/518.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #518.

docs/archive/518.html, src/518.json
Hi @szabgab 
I have fixed the link to RECAPS as someone pointed out to me just now.
Many Thanks.
Best Regards,
Mohammad
=> Fixed the link to RECAPS pwc.

src/520.json, src/next.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #520.

src/522.json
Hi @szabgab 
Please review the draft. 
Apology for the delay.
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #522.

src/524.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #524.

src/526.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for next week newsletter #526.

src/528.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 528.

src/530.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 530.

src/532.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 532.

src/536.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added draft for week 536.

src/538.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 538.

src/540.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft newsletter for next week.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added new author Kaushik Tunuguntla.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added new author Peter Campbell Smith.

src/542.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 542.

src/544.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 544.

src/546.json
Hi @szabgab 
Apology for the delay.
Many Thanks.
Best Regards,
Mohammad
=> Draft for the week 546.

src/548.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added draft for week 548.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added new author Bruce Gray.

src/550.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 550.

src/552.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft proposal for week 552.

src/554.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Initial draft for the week 554.

src/554.json
=> Copy-editing for issue 554

src/555.json
Nothing major, just some minor tweaks.
Closes #445
=> Copy-editing for issue 555

src/556.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 556.

src/556.json
Hi @szabgab 
Please update the newsletter, sorry :-(
Many Thanks.
Best Regards,
Mohammad
=> - Fix the weekly challenge post.

src/557.json
=> Copy editing

src/558.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 558.

src/560.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for the week 560.

src/560.json
Copy-editing for issue 560.
Closes #459.
=> Copy-editing issue #560

src/562.json
Hi @szabgab 
Perl blog is getting harder and harder these days.
Many Thanks.
Best Regards
=> - Added draft for week 562.

src/564.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 564.

src/566.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for the week 566.

src/568.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 568.

src/570.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 570.

lib/PerlWeekly/Issue.pm
This also includes commits to remove a misguided TODO and tidy related code slightly.
=> Include proper RSS subject for the editorial

src/574.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 574.

src/576.json, src/authors.json
HI @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 576.

src/578.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for newsletter 578.

src/584.json, src/authors.json
Hi @szabgab 
Apology for the late submission.
Many Thanks.
Best Regards,
Mohammad
=> Draft for the week 584.

src/586.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added initial draft.

src/588.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for the week 588.

src/590.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for the week 590.

src/592.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 592.

src/594.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 594.

src/596.json, src/authors.json
Hi @szabgab 
Merry Christmas !!!
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 596.

src/598.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 598.

src/598.json
Hi @szabgab 
Please approve the PR.
This would fix the links to niceperl.
Many Thanks.
Best Regards,
Mohammad
=> Fixed niceperl links.

src/600.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=>  Draft for the week 600.

src/602.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 602.

src/604.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for the week 604.

src/606.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards.
Mohammad
=> Proposal for week 606.

src/607.json, src/authors.json
Hi @szabgab 
Please review the changes.
Many Thanks.
Best Regards,
Mohammad
=> - Added weekly challenge 208.

src/607.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Fixed typo in the edition 607 w.r.t weekly challenge.

src/612.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 612.

src/614.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mhammad
=> - Added draft for week 614.

src/616.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for week 616.

src/618.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 618.

src/622.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Initial draft for the week 622.

src/624.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for issue 624.

src/events.json
Inspired by Ovid and Scaffidi shouting Dammit Stevan, we're going to peek at Stevan's new module on GH instead of waiting for CPAN :grin:
=> add July Boston.PM

src/626.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for the week 626.

src/628.json
Hi @szabgab 
I have pushed the pull request having incomplete draft for next week newsletter as I am flying in 4 hours to India. I would reach the final destination on Sunday where I access to internet is not guaranteed. This is the reason I just submitted what I have got so far. If I do get internet access then I will finish it off. Otherwise please take care of it and publish it.
During the holiday periods, 4th Aug - 28th Aug, I can only share the JSON data for the weekly challenge every week. 
I will be back to editing from week 632.
Thank you for the help and sorry for the inconvenience.
Best Regards,
Mohammad
=> Draft for the next week newsletter.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added two new authors.

src/633.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Initial draft for week 633.

src/634.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added initial draft for week 634.

src/636.json, src/authors.json
Hi @szabgab 
Many Thanks,
Best Regards,
Mohammad
=> - Added initial draft for week 636.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added new author Yves Orton.

src/638.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Initial draft of week 638.

src/640.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Initial draft for week 640.

src/642.json, src/authors.json
Hi @szabgab 
Many Thanks,
Best Regards,
Mohammad
=> - Draft for week 642.

src/646.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added draft for week 646.

src/648.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for the week 648.

src/650.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for week 650.

src/652.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 652.

src/656.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 656.

src/658.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Proposed draft for week 658.

src/660.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for the week 660.

src/660.json
Unfortunately, the event was not announced in the newsletter. Maybe could be added so that people reading it on the web later in the day could know about it ?
=> Add Open Food Fact hackaton mention

src/662.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Initial draft for week 662.

src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added new author Reinier Maliepaard.

src/664.json, src/next.json, tt/index.tt
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 664.

src/666.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 666.

src/668.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Added draft for week 668.

src/670.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Initial draft for week 670.

src/672.json, src/authors.json, src/next.json, tt/index.tt
HI @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 672.

src/674.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 674.

src/674.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Fixed typo in the post.

src/676.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 676.

src/676.json
Hi @szabgab 
Please review and merge when you get time.
Many Thanks.
Best Regards,
Mohammad
=> Fixed typo.

src/678.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 268.

src/680.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft proposal for week 680.

src/682.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 682.

src/684.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 684.

src/authors.json
Hi @szabgab,
In this pull request, I am adding a new author to be introduced in the next week newsletter.
Many Thanks.
Best Regards,
Mohammad
=> New author Torgny Lyon added.

src/686.json, src/authors.json
Hi @szabgab,
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 686.

src/688.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> initial draft for week 688.

src/690.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Initial draft for week 690.

src/692.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 692.

src/events.json
=> Update events.json for Toronto.pm

src/696.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 696.

src/698.json, src/authors.json
Hi @szabgab,
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 698.

src/702.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 702.

src/704.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 704.

src/706.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> Initial draft for week 706.

src/708.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Proposed draft for week 708.

src/710.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 710.

src/712.json, src/authors.json, tt/index.tt
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 712.

src/events.json
There are the Paris.pm meetings for the next 3 months.
=> add the next Paris.pm meetings

docs/index.rss, docs/perlweekly.rss, lib/PerlWeekly/Issue.pm
Just what it says in the title.
=> Include chapter title in feed as RSS subject

src/714.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 714.

src/716.json, src/authors.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 716.

src/718.json, src/authors.json
Hi @szabgab,
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 718.

src/720.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 720.

tt/webpage.tt
This turned out to be incredibly easy :-)
=> Replace broken Twitter link with AddToAny

src/722.json, src/authors.json
Hi @szabgab,
Many Thanks.
Best Regards,
Mohammad
=> Draft for week 722

src/724.json, src/authors.json, tt/index.tt
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Added proposal for week 724/

src/728.json
Hi @szabgab 
Many Thanks.
Best Regards,
Mohammad
=> - Draft for week 728

src/730.json
Hi @szabgab,
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 730.

src/732.json
Hi @szabgab,
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 732.

src/736.json, src/authors.json
Hi @szabgab,
Many Thanks.
Best Regards,
Mohammad
=> Proposed draft for week 736.

src/740.json
HI @szabgab,
Again, I couldn't verify the content as support to generate the doc is still missing.
Many Thanks.
Best Regards,
Mohammad
=> - Added draft for week 740.
